/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchSessionIdReportRouteImport } from './routes/research.$sessionId.report'
import { Route as ResearchSessionIdLiveRouteImport } from './routes/research.$sessionId.live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSessionIdReportRoute = ResearchSessionIdReportRouteImport.update({
  id: '/research/$sessionId/report',
  path: '/research/$sessionId/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSessionIdLiveRoute = ResearchSessionIdLiveRouteImport.update({
  id: '/research/$sessionId/live',
  path: '/research/$sessionId/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/research/$sessionId/live': typeof ResearchSessionIdLiveRoute
  '/research/$sessionId/report': typeof ResearchSessionIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/research/$sessionId/live': typeof ResearchSessionIdLiveRoute
  '/research/$sessionId/report': typeof ResearchSessionIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/research/$sessionId/live': typeof ResearchSessionIdLiveRoute
  '/research/$sessionId/report': typeof ResearchSessionIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/research/$sessionId/live' | '/research/$sessionId/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/research/$sessionId/live' | '/research/$sessionId/report'
  id:
    | '__root__'
    | '/'
    | '/research/$sessionId/live'
    | '/research/$sessionId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResearchSessionIdLiveRoute: typeof ResearchSessionIdLiveRoute
  ResearchSessionIdReportRoute: typeof ResearchSessionIdReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$sessionId/report': {
      id: '/research/$sessionId/report'
      path: '/research/$sessionId/report'
      fullPath: '/research/$sessionId/report'
      preLoaderRoute: typeof ResearchSessionIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$sessionId/live': {
      id: '/research/$sessionId/live'
      path: '/research/$sessionId/live'
      fullPath: '/research/$sessionId/live'
      preLoaderRoute: typeof ResearchSessionIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResearchSessionIdLiveRoute: ResearchSessionIdLiveRoute,
  ResearchSessionIdReportRoute: ResearchSessionIdReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
